### PR TITLE
added World_Physical_Map, World_Shaded_Relief and World_Topo_Map from ESRI

### PR DESCRIPTION
**Pull request by djm93dev**
I've added World_Physical_Map, World_Shaded_Relief and World_Topo_Map tile sources from ESRI

### CODE REVIEW

**Comment by jbednar** [comment]
Great, thanks! Are there any others there that we are missing? The more the merrier!

**Comment by djm93dev** [comment]
Yes, there are more. I can go through them all and add anything missing in a separate pull request this weekend.

**Comment by ahuang11** [comment]
Thanks for adding all those!

I'm wondering if we should loop through tile_sources and render it here:
https://github.com/holoviz/geoviews/blob/main/examples/gallery/bokeh/tile_sources.ipynb

**Comment by ahuang11** [comment]
I created an issue to track the examples; we can just merge what you have currently. Thanks!
https://github.com/holoviz/geoviews/issues/658

**Pull request merged**
