### PR TITLE
Improvement of annotators

### LINKED ISSUE #526: annotators wont work in geoviews
Maybe linked to #462 

#### ALL software version info
Macos 11.5.2 
Chrome  93.0.4577.82

geoviews                  1.9.1                    pypi_0    pypi
geoviews-core             1.9.1              pyh06a4308_0
jupyter                   1.0.0            py39h6e9494a_6    conda-forge
jupyter_client            7.0.1              pyhd3eb1b0_0
jupyter_console           6.4.0              pyhd8ed1ab_0    conda-forge
jupyter_core              4.7.1            py39hecd8cb5_0
jupyterlab_pygments       0.1.2                      py_0
jupyterlab_widgets        1.0.2              pyhd8ed1ab_0    conda-forge
Jupyter kernel Python 3 (ipykernel)

I also try with 
geoviews                  1.9.1                      py_0    pyviz
and
geoviews                  1.9.1              pyhd8ed1ab_1    conda-forge

with the same result
#### Description of expected behavior and the observed behavior
With the example notebook
https://examples.pyviz.org/assets/ml_annotators.zip

I'm getting no annotation tools showing up, and the same Uncaught Error: Model 'geoviews.models.custom_tools.ClearTool' does not exist. This could be due to a widget or a custom model not being registered before first usage. message in the console.

#### Stack traceback and/or browser JavaScript console output
```
Uncaught Error: Model 'geoviews.models.custom_tools.ClearTool' does not exist. This could be due to a widget or a custom model not being registered before first usage.
    at u.get (eval at append_javascript (main.min.js?v=f1ffcc85342b2a9c45ba434c8f1ce101d995e4384bfa196254b0682e057f067d246c34e884bed8d784d3165a09864d5dc58f19b32fcab07130e8f9542f7c76a5:59195), <anonymous>:306:1010)
    at Function._instantiate_object (eval at append_javascript (main.min.js?v=f1ffcc85342b2a9c45ba434c8f1ce101d995e4384bfa196254b0682e057f067d246c34e884bed8d784d3165a09864d5dc58f19b32fcab07130e8f9542f7c76a5:59195), <anonymous>:305:4811)
    at Function._instantiate_references_json (eval at append_javascript (main.min.js?v=f1ffcc85342b2a9c45ba434c8f1ce101d995e4384bfa196254b0682e057f067d246c34e884bed8d784d3165a09864d5dc58f19b32fcab07130e8f9542f7c76a5:59195), <anonymous>:305:4999)
    at Function.from_json (eval at append_javascript (main.min.js?v=f1ffcc85342b2a9c45ba434c8f1ce101d995e4384bfa196254b0682e057f067d246c34e884bed8d784d3165a09864d5dc58f19b32fcab07130e8f9542f7c76a5:59195), <anonymous>:305:8497)
    at Object.t.embed_items_notebook (eval at append_javascript (main.min.js?v=f1ffcc85342b2a9c45ba434c8f1ce101d995e4384bfa196254b0682e057f067d246c34e884bed8d784d3165a09864d5dc58f19b32fcab07130e8f9542f7c76a5:59195), <anonymous>:729:2437)
    at embed_document (<anonymous>:5:22)
    at <anonymous>:8:5
    at <anonymous>:24:3
    at eval (eval at append_javascript (main.min.js?v=f1ffcc85342b2a9c45ba434c8f1ce101d995e4384bfa196254b0682e057f067d246c34e884bed8d784d3165a09864d5dc58f19b32fcab07130e8f9542f7c76a5:59195), <anonymous>:138:28)
    at Array.forEach (<anonymous>)
get @ VM67:306
_instantiate_object @ VM67:305
_instantiate_references_json @ VM67:305
from_json @ VM67:305
t.embed_items_notebook @ VM67:729
embed_document @ VM151:5
(anonymous) @ VM151:8
(anonymous) @ VM151:24
eval @ VM69:138
handle_add_output @ VM69:127
dispatch @ main.min.js?v=f1ffcc85342b2a9c45ba434c8f1ce101d995e4384bfa196254b0682e057f067d246c34e884bed8d784d3165a09864d5dc58f19b32fcab07130e8f9542f7c76a5:2
v.handle @ main.min.js?v=f1ffcc85342b2a9c45ba434c8f1ce101d995e4384bfa196254b0682e057f067d246c34e884bed8d784d3165a09864d5dc58f19b32fcab07130e8f9542f7c76a5:2
trigger @ main.min.js?v=f1ffcc85342b2a9c45ba434c8f1ce101d995e4384bfa196254b0682e057f067d246c34e884bed8d784d3165a09864d5dc58f19b32fcab07130e8f9542f7c76a5:2
(anonymous) @ main.min.js?v=f1ffcc85342b2a9c45ba434c8f1ce101d995e4384bfa196254b0682e057f067d246c34e884bed8d784d3165a09864d5dc58f19b32fcab07130e8f9542f7c76a5:2
each @ main.min.js?v=f1ffcc85342b2a9c45ba434c8f1ce101d995e4384bfa196254b0682e057f067d246c34e884bed8d784d3165a09864d5dc58f19b32fcab07130e8f9542f7c76a5:2
each @ main.min.js?v=f1ffcc85342b2a9c45ba434c8f1ce101d995e4384bfa196254b0682e057f067d246c34e884bed8d784d3165a09864d5dc58f19b32fcab07130e8f9542f7c76a5:2
trigger @ main.min.js?v=f1ffcc85342b2a9c45ba434c8f1ce101d995e4384bfa196254b0682e057f067d246c34e884bed8d784d3165a09864d5dc58f19b32fcab07130e8f9542f7c76a5:2
events.trigger @ main.min.js?v=f1ffcc85342b2a9c45ba434c8f1ce101d995e4384bfa196254b0682e057f067d246c34e884bed8d784d3165a09864d5dc58f19b32fcab07130e8f9542f7c76a5:54255
OutputArea.append_output @ main.min.js?v=f1ffcc85342b2a9c45ba434c8f1ce101d995e4384bfa196254b0682e057f067d246c34e884bed8d784d3165a09864d5dc58f19b32fcab07130e8f9542f7c76a5:58791
OutputArea.handle_output @ main.min.js?v=f1ffcc85342b2a9c45ba434c8f1ce101d995e4384bfa196254b0682e057f067d246c34e884bed8d784d3165a09864d5dc58f19b32fcab07130e8f9542f7c76a5:58693
output @ main.min.js?v=f1ffcc85342b2a9c45ba434c8f1ce101d995e4384bfa196254b0682e057f067d246c34e884bed8d784d3165a09864d5dc58f19b32fcab07130e8f9542f7c76a5:60519
Kernel._handle_output_message @ main.min.js?v=f1ffcc85342b2a9c45ba434c8f1ce101d995e4384bfa196254b0682e057f067d246c34e884bed8d784d3165a09864d5dc58f19b32fcab07130e8f9542f7c76a5:62280
i @ main.min.js?v=f1ffcc85342b2a9c45ba434c8f1ce101d995e4384bfa196254b0682e057f067d246c34e884bed8d784d3165a09864d5dc58f19b32fcab07130e8f9542f7c76a5:2
Kernel._handle_iopub_message @ main.min.js?v=f1ffcc85342b2a9c45ba434c8f1ce101d995e4384bfa196254b0682e057f067d246c34e884bed8d784d3165a09864d5dc58f19b32fcab07130e8f9542f7c76a5:62320
Kernel._finish_ws_message @ main.min.js?v=f1ffcc85342b2a9c45ba434c8f1ce101d995e4384bfa196254b0682e057f067d246c34e884bed8d784d3165a09864d5dc58f19b32fcab07130e8f9542f7c76a5:62099
(anonymous) @ main.min.js?v=f1ffcc85342b2a9c45ba434c8f1ce101d995e4384bfa196254b0682e057f067d246c34e884bed8d784d3165a09864d5dc58f19b32fcab07130e8f9542f7c76a5:62090
Promise.then (async)
Kernel._handle_ws_message @ main.min.js?v=f1ffcc85342b2a9c45ba434c8f1ce101d995e4384bfa196254b0682e057f067d246c34e884bed8d784d3165a09864d5dc58f19b32fcab07130e8f9542f7c76a5:62090
i @ main.min.js?v=f1ffcc85342b2a9c45ba434c8f1ce101d995e4384bfa196254b0682e057f067d246c34e884bed8d784d3165a09864d5dc58f19b32fcab07130e8f9542f7c76a5:2
```

#### Screenshots or screencasts of the bug in action

Capture d’écran 2021-09-21 à 21-09-21 11 24 27

### LINKED ISSUE #576: Locations in hvplot raises warning
#### ALL software version info
``` yaml
geoviews   : 1.9.5
holoviews  : 1.15.0a2
hvplot     : 0.8.0
```

#### Description of expected behavior and the observed behavior
When having features like `coastline` called by `hvplot` a warning is given with the latest dev release of `holoviews`. The warning is not present with version 1.14.

I have added the bug in Geoviews as this is where the warning is emitted from:
 
https://github.com/holoviz/geoviews/blob/1bd771233dfbd1208e86224f987c9003f121164a/geoviews/element/geo.py#L149-L150

#### Complete, minimal, self-contained example code that reproduces the issue

``` python
import xarray as xr
import hvplot.xarray

data = xr.tutorial.open_dataset("rasm").load()['Tair'].isel(time=0)
data.hvplot.quadmesh('xc', 'yc', coastline=True)

```

#### Screenshots or screencasts of the bug in action
With `holoviews` 1.15:
image

With `holoviews` 1.14:
image

### PR DESCRIPTION
**Pull request by Hoxbro**
Fixes  #526
Fixes problems seen in [Annotators](https://pyviz-dev.github.io/geoviews/user_guide/Annotators.html). 

**Things done:**
- Added function `transform_shapely_to_wsg84` as large coordinates shows a blank shapely figure. Also visible on the [website](https://pyviz-dev.github.io/geoviews/user_guide/Annotators.html).  

| Before   |  After |
|----------|-------------|
| image |  image |

- Converted string to pathlib.
image

- Update hover and link code with correct projection functions. Used this [example](https://github.com/bokeh/bokeh/blob/branch-3.0/examples/plotting/file/customjs_hover.py).

- Changed `.opts` to `.options`, though I'm not entirely sure if this is the correct fix. 

**Things not done:**
- <s> I did not see this error mentioned in #526 when running the notebook.  </s>
- I did see the error mentioned in #526 on a clean installed virtual machine. 
- When moving a point around an annotation, the annotations logic disappears. See #584.

**TODO**
- [ ] Make unit test for transform_shapely_to_wsg84

### CODE REVIEW

**Comment by philippjfr** [comment]
The geometry not being visible is definitely an issue but I'm not sure I love the fix. I would expect the geometry returned by the element to match the `crs` of that element. Is this a known issue in shapely or do large coordinate values actually get stored incorrectly causing the issue?

**Comment by Hoxbro** [comment]
The SVG created by shapely doesn't show up in the notebook. It seems to be related to Jupyter as far as I can see:



If I open the saved file in Inkscape, it renders correctly:




It seems to be a known issue: https://github.com/shapely/shapely/issues/574 

<details>

  <summary>Code </summary>


``` python
from IPython.display import SVG, display
from shapely.geometry import MultiPoint, Point

yy = [-10131185, -10131943, -10131766, -10131032]
xx = [3805587, 3803182, 3801073, 3799778]

points = [Point(x, y) for (x, y) in zip(xx, yy)]
multi = MultiPoint(points)

multi._repr_svg_()

with open("tmp.svg", "w") as f:
    f.write(multi._repr_svg_())
```

<details>

**Comment by philippjfr** [comment]
Thanks for investigating that. If it's a known bug in shapely I'm a strong -1 in changing our behavior. What I would be in favor of is to add a `projection` argument to the `geom` methods that lets you easily project the geometry to some other coordinate system, e.g. `WGS84`. Then we can update the notebooks so they don't look broken while maintaining the existing correct default behavior.

**Comment by Hoxbro** [comment]
Completely agree with you. 

I have implemented this suggestion. I have removed the flip from `transform_shapely`, which means that the output of `.geom()` is rotated compared to the bokeh plot. I can add this back. 

image

Another thing is I added an extra point in the first example to avoid #584.

**Comment by philippjfr** [comment]
Hmm, I guess I'm confused about that. Why is the svg rotated? When I load shapely objects via geopandas for example they use the same convention for storing x/y that we do and do not appear to be flipped.

**Comment by Hoxbro** [comment]
After some digging this is because I use `wgs84` instead of `PlateCarree()`, which I thought was the same thing. Should an option of setting `projection=True` use `PlateCarree` or will this be too complicated?

image

**Comment by Hoxbro** [comment]
Issue https://github.com/holoviz/geoviews/issues/584 is also a problem with 5 points. I will update the issue with more information.

**Review by philippjfr — APPROVED** [review]
Thanks, I think this is a big improvement.

**Pull request merged**
